from .. import Provider as BaseProvider
from _typeshed import Incomplete

def ssn_checksum(number: str) -> int: ...
def vat_checksum(number: str) -> int: ...

class Provider(BaseProvider):
    vat_id_formats: Incomplete
    def vat_id(self) -> str: ...
    ssn_formats: Incomplete
    def ssn(self) -> str: ...
