from ..en_PH import Provider as EnPhProvider
from _typeshed import Incomplete

class Provider(EnPhProvider):
    catch_phrase_formats: Incomplete
    noun_ish_good_traits: Incomplete
    good_service_adjectives: Incomplete
    objects_of_concern: Incomplete
    def random_noun_ish_good_trait(self) -> str: ...
    def random_good_service_adjective(self) -> str: ...
    def random_good_service_adjective_chain(self) -> str: ...
    def random_object_of_concern(self) -> str: ...
    def english_catch_phrase(self) -> str: ...
    def catch_phrase(self) -> str: ...
