from .. import Provider as AddressProvider
from _typeshed import Incomplete

class Provider(AddressProvider):
    address_formats: Incomplete
    building_number_formats: Incomplete
    countries: Incomplete
    prefectures: Incomplete
    cities: Incomplete
    towns: Incomplete
    building_names: Incomplete
    def administrative_unit(self) -> str: ...
    prefecture = administrative_unit
    def city(self) -> str: ...
    def town(self) -> str: ...
    def chome(self) -> str: ...
    def ban(self) -> str: ...
    def gou(self) -> str: ...
    def building_name(self) -> str: ...
    def postcode(self) -> str: ...
    def zipcode(self) -> str: ...
