from .. import Provider as AutomotiveProvider
from _typeshed import Incomplete
from faker.providers.person.bn_BD import translate_to_bengali_digits as translate_to_bengali_digits

class Provider(AutomotiveProvider):
    cities: Incomplete
    vehicle_category_letters: Incomplete
    vehicle_category_numbers: Incomplete
    vehicle_serial_number_formats: Incomplete
    license_plate_formats: Incomplete
    def city_name(self) -> str: ...
    def vehicle_category_letter(self) -> str: ...
    def vehicle_category_number(self) -> str: ...
    def vehicle_serial_number(self) -> str: ...
    def license_plate(self) -> str: ...
