from .. import Provider as PersonProvider
from _typeshed import Incomplete
from typing import Tuple

class Provider(PersonProvider):
    first_name_female_pairs: Incomplete
    first_names_female: Incomplete
    first_kana_names_female: Incomplete
    first_romanized_names_female: Incomplete
    first_name_male_pairs: Incomplete
    first_names_male: Incomplete
    first_kana_names_male: Incomplete
    first_romanized_names_male: Incomplete
    first_names: Incomplete
    first_kana_names: Incomplete
    first_romanized_names: Incomplete
    first_name_pairs: Incomplete
    last_name_pairs: Incomplete
    last_names: Incomplete
    last_kana_names: Incomplete
    last_romanized_names: Incomplete
    formats_male: Incomplete
    formats_female: Incomplete
    formats: Incomplete
    kana_formats_male: Incomplete
    kana_formats_female: Incomplete
    kana_formats: Incomplete
    romanized_formats_male: Incomplete
    romanized_formats_female: Incomplete
    romanized_formats: Incomplete
    def first_name_pair(self) -> Tuple[str, str, str]: ...
    def first_name_male_pair(self) -> Tuple[str, str, str]: ...
    def first_name_female_pair(self) -> Tuple[str, str, str]: ...
    def last_name_pair(self) -> Tuple[str, str, str]: ...
    def first_name(self) -> str: ...
    def first_name_male(self) -> str: ...
    def first_name_female(self) -> str: ...
    def last_name(self) -> str: ...
    def first_kana_name(self) -> str: ...
    def first_kana_name_male(self) -> str: ...
    def first_kana_name_female(self) -> str: ...
    def last_kana_name(self) -> str: ...
    def first_romanized_name(self) -> str: ...
    def first_romanized_name_male(self) -> str: ...
    def first_romanized_name_female(self) -> str: ...
    def last_romanized_name(self) -> str: ...
    def kana_name(self) -> str: ...
    def kana_name_male(self) -> str: ...
    def kana_name_female(self) -> str: ...
    def romanized_name(self) -> str: ...
    def romanized_name_male(self) -> str: ...
    def romanized_name_female(self) -> str: ...
