from .. import Provider as InternetProvider
from _typeshed import Incomplete
from faker.utils.decorators import slugify_domain as slugify_domain

class Provider(InternetProvider):
    free_email_domains: Incomplete
    tlds: Incomplete
    def user_name(self) -> str: ...
    def domain_word(self) -> str: ...

def remove_accents(value: str) -> str: ...
def latinize(value: str) -> str: ...
