from .. import Provider as AddressProvider
from _typeshed import Incomplete

class Provider(AddressProvider):
    area_names: Incomplete
    building_names: Incomplete
    building_number_formats: Incomplete
    city_prefixes: Incomplete
    city_suffixes: Incomplete
    cities: Incomplete
    countries: Incomplete
    secondary_address_formats: Incomplete
    street_suffixes: Incomplete
    postcode_formats: Incomplete
    street_name_formats: Incomplete
    street_address_formats: Incomplete
    town_formats: Incomplete
    address_formats: Incomplete
    def administrative_unit(self) -> str: ...
    def area_name(self) -> str: ...
    def building_name(self) -> str: ...
    def building_number(self) -> str: ...
    def city_prefix(self) -> str: ...
    def city(self) -> str: ...
    def postcode(self) -> str: ...
    def secondary_address(self) -> str: ...
    def town(self) -> str: ...
