from .. import Provider as AutomotiveProvider
from _typeshed import Incomplete

class Provider(AutomotiveProvider):
    license_plate_old_format_first_letters: str
    license_plate_old_format_second_letters: str
    license_plate_new_format_letters: str
    license_formats: Incomplete
    def license_plate_old(self) -> str: ...
    def license_plate_new(self) -> str: ...
    def license_plate_police(self) -> str: ...
    def license_plate_temporary(self) -> str: ...
    def license_plate_diplomatic(self) -> str: ...
    def license_plate(self) -> str: ...
