from _typeshed import Incomplete

class BaseFakerException(Exception): ...
class UniquenessException(BaseFakerException): ...

class UnsupportedFeature(BaseFakerException):
    name: str
    def __init__(self, msg: str, name: str) -> None: ...
