from .. import Provider as AddressProvider
from _typeshed import Incomplete

class Provider(AddressProvider):
    street_suffixes: Incomplete
    street_name_formats: Incomplete
    city_formats: Incomplete
    street_address_formats: Incomplete
    address_formats: Incomplete
    frequent_street_names: Incomplete
    real_city_names: Incomplete
    city_prefs: Incomplete
    city_parts: Incomplete
    city_suffixes: Incomplete
    counties: Incomplete
    countries: Incomplete
    def administrative_unit(self) -> str: ...
    county = administrative_unit
    def street_address_with_county(self) -> str: ...
    def city_prefix(self) -> str: ...
    def city_part(self) -> str: ...
    def real_city_name(self) -> str: ...
    def frequent_street_name(self) -> str: ...
    def postcode(self) -> str: ...
    def street_name(self) -> str: ...
    def building_number(self) -> str: ...
