from ... import BaseProvider as BaseProvider
from _typeshed import Incomplete

class Provider(BaseProvider):
    sss_formats: Incomplete
    gsis_formats: Incomplete
    philhealth_formats: Incomplete
    pagibig_formats: Incomplete
    umid_formats: Incomplete
    def sss(self) -> str: ...
    def gsis(self) -> str: ...
    def pagibig(self) -> str: ...
    def philhealth(self) -> str: ...
    def umid(self) -> str: ...
    def ssn(self) -> str: ...
