from .. import BaseProvider as BaseProvider, ElementsType as ElementsType

class Provider(BaseProvider):
    user_agents: ElementsType[str]
    windows_platform_tokens: ElementsType[str]
    linux_processors: ElementsType[str]
    mac_processors: ElementsType[str]
    android_versions: ElementsType[str]
    apple_devices: ElementsType[str]
    ios_versions: ElementsType[str]
    def mac_processor(self) -> str: ...
    def linux_processor(self) -> str: ...
    def user_agent(self) -> str: ...
    def chrome(self, version_from: int = 13, version_to: int = 63, build_from: int = 800, build_to: int = 899) -> str: ...
    def firefox(self) -> str: ...
    def safari(self) -> str: ...
    def opera(self) -> str: ...
    def internet_explorer(self) -> str: ...
    def windows_platform_token(self) -> str: ...
    def linux_platform_token(self) -> str: ...
    def mac_platform_token(self) -> str: ...
    def android_platform_token(self) -> str: ...
    def ios_platform_token(self) -> str: ...
