from .. import Provider as BarcodeProvider
from _typeshed import Incomplete

class Provider(BarcodeProvider):
    local_prefixes: Incomplete
    def jan(self, length: int = 13) -> str: ...
    def jan8(self) -> str: ...
    def jan13(self) -> str: ...
