from .. import Provider as AddressProvider
from _typeshed import Incomplete

class Provider(AddressProvider):
    address_formats: Incomplete
    building_number_formats: Incomplete
    city_formats: Incomplete
    street_address_formats: Incomplete
    street_name_formats: str
    city_prefixes: Incomplete
    city_names: Incomplete
    region_names: Incomplete
    countries: Incomplete
    street_prefixes: Incomplete
    street_titles: Incomplete
    def city_prefix(self) -> str: ...
    def city_name(self) -> str: ...
    def postcode(self) -> str: ...
    def street_prefix(self) -> str: ...
    def street_name(self) -> str: ...
    def street_title(self) -> str: ...
    def region(self) -> str: ...
