from .. import Provider as PhoneNumberProvider
from _typeshed import Incomplete

class Provider(PhoneNumberProvider):
    cellphone_formats: Incomplete
    telephone_formats: Incomplete
    services_phones_formats: Incomplete
    formats: Incomplete
    def operator_id(self) -> str: ...
    def area_code(self) -> str: ...
    def cellphone_number(self) -> str: ...
    def telephone_number(self) -> str: ...
    def service_phone_number(self) -> str: ...
    def phone_number(self) -> str: ...
