from .. import Provider as CompanyProvider
from _typeshed import Incomplete

class Provider(CompanyProvider):
    formats: Incomplete
    company_suffixes: Incomplete
    company_prefixes: Incomplete
    company_types: Incomplete
    name_complements: Incomplete
    company_adjectives: Incomplete
    def company_type(self) -> str: ...
    def company_suffix(self) -> str: ...
    def random_name_complements(self) -> str: ...
    def random_company_adjective(self) -> str: ...
    def random_company_acronym(self) -> str: ...
    def company_prefix(self) -> str: ...
