from .. import Provider as AddressProvider
from ... import ElementsType as ElementsType
from _typeshed import Incomplete

class Provider(AddressProvider):
    metro_manila_postcodes: Incomplete
    luzon_province_postcodes: Incomplete
    visayas_province_postcodes: Incomplete
    mindanao_province_postcodes: Incomplete
    postcodes: Incomplete
    metro_manila_lgus: Incomplete
    province_lgus: Incomplete
    luzon_provinces: Incomplete
    visayas_provinces: Incomplete
    mindanao_provinces: Incomplete
    provinces: Incomplete
    partitioned_building_number_formats: Incomplete
    building_unit_number_formats: Incomplete
    building_name_formats: Incomplete
    building_name_suffixes: Incomplete
    subdivision_unit_number_formats: Incomplete
    subdivision_name_formats: Incomplete
    subdivision_name_suffixes: Incomplete
    floor_numbers: Incomplete
    street_suffixes: Incomplete
    street_name_formats: Incomplete
    street_address_formats: Incomplete
    metro_manila_address_formats: Incomplete
    luzon_province_address_formats: Incomplete
    visayas_province_address_formats: Incomplete
    mindanao_province_address_formats: Incomplete
    address_formats: Incomplete
    def metro_manila_postcode(self) -> str: ...
    def luzon_province_postcode(self) -> str: ...
    def visayas_province_postcode(self) -> str: ...
    def mindanao_province_postcode(self) -> str: ...
    def postcode(self) -> str: ...
    def luzon_province(self) -> str: ...
    def visayas_province(self) -> str: ...
    def mindanao_province(self) -> str: ...
    def administrative_unit(self) -> str: ...
    province = administrative_unit
    def standalone_building_number(self) -> str: ...
    def partitioned_building_number(self) -> str: ...
    def building_number(self) -> str: ...
    def ordinal_street_number(self) -> str: ...
    def floor_number(self) -> str: ...
    def ordinal_floor_number(self) -> str: ...
    def floor_unit_number(self) -> str: ...
    def building_unit_number(self) -> str: ...
    def building_name(self) -> str: ...
    def building_name_suffix(self) -> str: ...
    def subdivision_block_number(self) -> str: ...
    def subdivision_lot_number(self) -> str: ...
    def subdivision_unit_number(self) -> str: ...
    def subdivision_name(self) -> str: ...
    def subdivision_name_suffix(self) -> str: ...
    def metro_manila_lgu(self) -> str: ...
    def province_lgu(self) -> str: ...
    def metro_manila_address(self) -> str: ...
    def luzon_province_address(self) -> str: ...
    def visayas_province_address(self) -> str: ...
    def mindanao_province_address(self) -> str: ...
    def address(self) -> str: ...
