from .. import Provider as BaseProvider
from _typeshed import Incomplete

def nit_check_digit(nit: str) -> str: ...

class Provider(BaseProvider):
    nuip_formats: Incomplete
    legal_person_nit_formats: Incomplete
    def nuip(self) -> str: ...
    natural_person_nit = nuip
    def natural_person_nit_with_check_digit(self) -> str: ...
    def legal_person_nit(self) -> str: ...
    def legal_person_nit_with_check_digit(self) -> str: ...
