from .. import Provider as AutomotiveProvider
from _typeshed import Incomplete

class Provider(AutomotiveProvider):
    license_plate_letters: Incomplete
    vehicle_categories: Incomplete
    license_plate_suffix: Incomplete
    license_plate_formats: Incomplete
    plate_number_formats: Incomplete
    plate_extra_formats: Incomplete
    plate_special_formats: Incomplete
    def license_plate(self) -> str: ...
    def plate_letter(self) -> str: ...
    def plate_number(self) -> str: ...
    def plate_number_extra(self) -> str: ...
    def plate_number_special(self) -> str: ...
    def plate_suffix(self) -> str: ...
    def vehicle_category(self) -> str: ...
