from .. import Provider as SsnProvider
from _typeshed import Incomplete
from faker.utils.checksums import calculate_luhn as calculate_luhn
from typing import Tuple

class Provider(SsnProvider):
    def ssn(self, min_age: int = 18, max_age: int = 90, long: bool = False, dash: bool = True) -> str: ...
    ORG_ID_DIGIT_1: Incomplete
    def org_id(self, long: bool = False, dash: bool = True) -> str: ...
    def vat_id(self) -> str: ...
    def org_and_vat_id(self, long: bool = False, dash: bool = True) -> Tuple[str, str]: ...
