from .. import Provider as AddressProvider
from _typeshed import Incomplete

class Provider(AddressProvider):
    city_formats: Incomplete
    city_suffixes: Incomplete
    street_suffixes: Incomplete
    village_suffixes: Incomplete
    district_suffixes: Incomplete
    settlement_suffixes: Incomplete
    building_number_formats: Incomplete
    house_number_formats: Incomplete
    address_formats: Incomplete
    street_name_formats: Incomplete
    cities: Incomplete
    countries: Incomplete
    districts: Incomplete
    settlements: Incomplete
    streets: Incomplete
    villages: Incomplete
    def house_number(self): ...
    def city(self): ...
    def city_suffix(self): ...
    def street(self): ...
    def street_suffix(self): ...
    def village(self): ...
    def village_suffix(self): ...
    def district(self): ...
    def district_suffix(self): ...
    def settlement(self): ...
    def settlement_suffix(self): ...
    def administrative_unit(self): ...
    def postcode(self): ...
    def postalcode(self): ...
