from .. import Provider as BaseProvider
from _typeshed import Incomplete

class Provider(BaseProvider):
    vat_id_formats: Incomplete
    def vat_id(self) -> str: ...
    def nie(self) -> str: ...
    def nif(self) -> str: ...
    def cif(self) -> str: ...
    def doi(self) -> str: ...
    def nuss(self, company: bool = False) -> str: ...
