from ..utils import text as text
from typing import Callable, TypeVar

T = TypeVar('T')

def slugify(fn: Callable) -> Callable: ...
def slugify_domain(fn: Callable) -> Callable: ...
def slugify_unicode(fn: Callable) -> Callable: ...
def lowercase(fn: Callable) -> Callable: ...
