from .. import Provider as SsnProvider
from _typeshed import Incomplete
from datetime import datetime
from typing import List

def checksum(digits: List[int]) -> int: ...
def calculate_month(birth_date: datetime) -> int: ...

class Provider(SsnProvider):
    def ssn(self) -> str: ...
    vat_id_formats: Incomplete
    def vat_id(self) -> str: ...
