from .. import Provider as MiscProvider
from _typeshed import Incomplete

class Provider(MiscProvider):
    gemstone_names: Incomplete
    mountain_names: Incomplete
    plant_names: Incomplete
    space_object_names: Incomplete
    random_object_names: Incomplete
    def gemstone_name(self) -> str: ...
    def mountain_name(self) -> str: ...
    def plant_name(self) -> str: ...
    def space_object_name(self) -> str: ...
    def random_object_name(self) -> str: ...
