from .. import Provider as CompanyProvider
from _typeshed import Incomplete
from typing import List

def regon_checksum(digits: List[int]) -> int: ...
def local_regon_checksum(digits: List[int]) -> int: ...
def company_vat_checksum(digits: List[int]) -> int: ...

class Provider(CompanyProvider):
    formats: Incomplete
    company_prefixes: Incomplete
    company_suffixes: Incomplete
    def company_prefix(self) -> str: ...
    def regon(self) -> str: ...
    def local_regon(self) -> str: ...
    def company_vat(self) -> str: ...
