from .. import Provider as BaseProvider

class Provider(BaseProvider):
    INVALID_SSN_TYPE: str
    SSN_TYPE: str
    ITIN_TYPE: str
    EIN_TYPE: str
    def itin(self) -> str: ...
    def ein(self) -> str: ...
    def invalid_ssn(self) -> str: ...
    def ssn(self, taxpayer_identification_number_type: str = ...) -> str: ...
