from .. import BaseProvider as BaseProvider, ElementsType as ElementsType, date_time as date_time

localized: bool

class Provider(BaseProvider):
    city_suffixes: ElementsType[str]
    street_suffixes: ElementsType[str]
    city_formats: ElementsType[str]
    street_name_formats: ElementsType[str]
    street_address_formats: ElementsType[str]
    address_formats: ElementsType[str]
    building_number_formats: ElementsType[str]
    postcode_formats: ElementsType[str]
    countries: ElementsType[str]
    ALPHA_2: str
    ALPHA_3: str
    alpha_2_country_codes: ElementsType[str]
    alpha_3_country_codes: ElementsType[str]
    def city_suffix(self) -> str: ...
    def street_suffix(self) -> str: ...
    def building_number(self) -> str: ...
    def city(self) -> str: ...
    def street_name(self) -> str: ...
    def street_address(self) -> str: ...
    def postcode(self) -> str: ...
    def address(self) -> str: ...
    def country(self) -> str: ...
    def country_code(self, representation: str = ...) -> str: ...
    def current_country_code(self) -> str: ...
    def current_country(self) -> str: ...
