import ast

class SampleCodeValidator(ast.NodeVisitor):
    def __init__(self, command) -> None: ...
    @property
    def errors(self): ...
    def visit(self, node): ...
    def visit_Call(self, node) -> None: ...
    def visit_Attribute(self, node) -> None: ...
    def visit_Name(self, node) -> None: ...
