from .. import Provider as AddressProvider
from _typeshed import Incomplete

class Provider(AddressProvider):
    cities: Incomplete
    street_prefixes: Incomplete
    streets: Incomplete
    regions: Incomplete
    building_number_formats: Incomplete
    postcode_formats: Incomplete
    street_address_formats: Incomplete
    address_formats: Incomplete
    def street_prefix(self) -> str: ...
    def street_prefix_short(self) -> str: ...
    def street_name(self) -> str: ...
    def city(self) -> str: ...
    def administrative_unit(self) -> str: ...
    def postcode(self) -> str: ...
    def zipcode(self) -> str: ...
    def postalcode(self) -> str: ...
    region = administrative_unit
