from .. import Provider as DateParseTypeProvider
from ....typing import DateParseType as DateParseType
from datetime import datetime
from typing import Optional

def thai_strftime(dt_obj: datetime, fmt: str = '%-d %b %Y', thai_digit: bool = False, buddhist_era: bool = True) -> str: ...

class Provider(DateParseTypeProvider):
    def date(self, pattern: str = '%-d %b %Y', end_datetime: Optional[DateParseType] = None, thai_digit: bool = False, buddhist_era: bool = True) -> str: ...
    def time(self, pattern: str = '%H:%M:%S', end_datetime: Optional[DateParseType] = None, thai_digit: bool = False) -> str: ...
    def century(self, thai_digit: bool = False, buddhist_era: bool = True) -> str: ...
