from .. import Provider as SsnProvider
from typing import List

def checksum(digits: List[int]) -> int: ...

class Provider(SsnProvider):
    def ssn(self) -> str: ...
    def cpf(self) -> str: ...
    def rg(self) -> str: ...
