from .. import Provider as SsnProvider
from ....typing import SexLiteral as SexLiteral
from datetime import date
from typing import Optional

def select_gender(gender: SexLiteral) -> int: ...
def calculate_day_count(birthday: date) -> int: ...
def calculate_check_sum(val: str) -> int: ...

class Provider(SsnProvider):
    def ssn(self, birthday: Optional[str] = None, gender: Optional[SexLiteral] = None) -> str: ...
