from .. import Provider as PhoneNumberProvider
from _typeshed import Incomplete

class Provider(PhoneNumberProvider):
    formats: Incomplete
    landline_codes: Incomplete
    special_codes: Incomplete
    cellphone_blocks: Incomplete
    def landline_code(self) -> str: ...
    def cellphone_block(self) -> str: ...
    def special_code(self) -> str: ...
    def phone_number(self) -> str: ...
