from .. import Provider as CompanyProvider
from _typeshed import Incomplete
from typing import List

def company_id_checksum(digits: List[int]) -> List[int]: ...

class Provider(CompanyProvider):
    formats: Incomplete
    catch_phrase_formats: Incomplete
    nouns: Incomplete
    verbs: Incomplete
    attributes: Incomplete
    company_suffixes: Incomplete
    def catch_phrase_noun(self) -> str: ...
    def catch_phrase_attribute(self) -> str: ...
    def catch_phrase_verb(self) -> str: ...
    def catch_phrase(self) -> str: ...
    def company_id(self) -> str: ...
    def cnpj(self) -> str: ...
