from .. import BaseProvider as BaseProvider
from typing import Dict, Optional

localized: bool
default_locale: str

class Provider(BaseProvider):
    ALPHA: Dict[str, str]
    bban_format: str
    country_code: str
    def aba(self) -> str: ...
    def bank_country(self) -> str: ...
    def bban(self) -> str: ...
    def iban(self) -> str: ...
    def swift8(self, use_dataset: bool = False) -> str: ...
    def swift11(self, primary: bool = False, use_dataset: bool = False) -> str: ...
    def swift(self, length: Optional[int] = None, primary: bool = False, use_dataset: bool = False) -> str: ...
