from ... import BaseProvider as BaseProvider
from typing import Tuple

class Provider(BaseProvider):
    globe_mobile_number_prefixes: Tuple[str, ...]
    smart_mobile_number_prefixes: Tuple[str, ...]
    sun_mobile_number_prefixes: Tuple[str, ...]
    globe_mobile_number_formats: Tuple[str, ...]
    smart_mobile_number_formats: Tuple[str, ...]
    sun_mobile_number_formats: Tuple[str, ...]
    mobile_number_formats: Tuple[str, ...]
    bayantel_landline_identifiers: Tuple[str, ...]
    misc_landline_identifiers: Tuple[str, ...]
    non_area2_landline_area_codes: Tuple[str, ...]
    globe_area2_landline_number_formats: Tuple[str, ...]
    pldt_area2_landline_number_formats: Tuple[str, ...]
    bayantel_area2_landline_number_formats: Tuple[str, ...]
    misc_area2_landline_number_formats: Tuple[str, ...]
    area2_landline_number_formats: Tuple[str, ...]
    non_area2_landline_number_formats: Tuple[str, ...]
    landline_number_formats: Tuple[str, ...]
    def globe_mobile_number_prefix(self) -> str: ...
    def smart_mobile_number_prefix(self) -> str: ...
    def sun_mobile_number_prefix(self) -> str: ...
    def bayantel_landline_identifier(self) -> str: ...
    def misc_landline_identifier(self) -> str: ...
    def non_area2_landline_area_code(self) -> str: ...
    def globe_mobile_number(self) -> str: ...
    def smart_mobile_number(self) -> str: ...
    def sun_mobile_number(self) -> str: ...
    def mobile_number(self) -> str: ...
    def globe_area2_landline_number(self) -> str: ...
    def pldt_area2_landline_number(self) -> str: ...
    def bayantel_area2_landline_number(self) -> str: ...
    def misc_area2_landline_number(self) -> str: ...
    def area2_landline_number(self) -> str: ...
    def non_area2_landline_number(self) -> str: ...
    def landline_number(self) -> str: ...
