from .. import Provider as CompanyProvider
from _typeshed import Incomplete

def calculate_checksum(value: str) -> str: ...

class Provider(CompanyProvider):
    formats: Incomplete
    company_prefixes: Incomplete
    company_suffixes: Incomplete
    large_companies: Incomplete
    catch_phrase_adj: Incomplete
    catch_phrase_nouns_masc: Incomplete
    catch_phrase_nouns_fem: Incomplete
    catch_phrase_nouns_neu: Incomplete
    bsWords: Incomplete
    def catch_phrase(self) -> str: ...
    def large_company(self) -> str: ...
    def company_prefix(self) -> str: ...
    def businesses_inn(self) -> str: ...
    def individuals_inn(self) -> str: ...
    def businesses_ogrn(self) -> str: ...
    def individuals_ogrn(self) -> str: ...
    def kpp(self) -> str: ...
